# Test  Questions 

# Q-1 Difference between python version 2 and version 3 ? how do you check current version of python ?

# Ans: Python 2 and Python 3 are two major versions of the Python programming language, and they have some key differences. Here are some of the significant distinctions:
# Print Statement:

# Python 2: Uses the print statement without parentheses, like print "Hello".

# Python 3: Requires parentheses for the print function, like print("Hello").

# Integer Division:

# Python 2: Performs integer division by default. For example, 5 / 2 would result in 2.

# Python 3: Performs true division by default. For example, 5 / 2 would result in 2.5.

# Unicode Support:

# Python 2: Strings are ASCII by default, and Unicode support is available

# Python 3: Strings are Unicode by default.

To check the current version of Python, you can open a terminal or command prompt and type the following command:

# python --version

# python3 --version





# Q- 2 Difference between local variable and global variable ?exaples?



# Ans: Global variables are accessible throughout the entire program, while local variables are only accessible within the function or block they are declared in.

`a global variable is a variable that is declared outside all functions or blocks. Because of its scope, it can be accessed and modified by any part of the code, making it globally available.

a local variable is a variable that is declared within a function or a block. Its scope is limited to that function or block, meaning it can't be accessed or modified by code outside of that function or block.

In [6]:
# Example
def my_function():
    # Local variable 'x' is declared inside the function
    x = 10
    print("Inside the function, x =", x)

# Call the function
my_function()




Inside the function, x = 10


In [8]:
# Example 2
# Global variable 'y' is declared outside any function
y = 20

def another_function():
    # Accessing the global variable 'y' inside the function
    print("Inside the function, y =", y)

# Call the function
another_function()

# Global variables are accessible outside functions
print("Outside the function, y =", y)


Inside the function, y = 20
Outside the function, y = 20


# Q- 3 Waht are data types in python ?

Ans
 In Python, data types are classifications that categorize various types of data, indicating the operations that can be performed on them and the way they are stored. Python has several built-in data types, and they can be broadly categorized into the following:
 
int: Integer type represents whole numbers without any decimal points. For example, 5, -10, 1000.
 
float: Float type represents numbers with decimal points or in exponential form. For example, 3.14, 2.0, 1.5e2.

str: String type represents a sequence of characters. Strings are immutable in Python. For example, 'hello', "world".

list: List is a mutable sequence that can contain elements of different data types. For example, [1, 2, 3], ['apple', 'orange', 'banana'].

set: Set is an unordered collection of unique elements. For example, {1, 2, 3}, {'apple', 'orange', 'banana'}.

dict: Dictionary is a collection of key-value pairs. Each key must be unique. For example, {'name': 'John', 'age': 25}.

bool: Boolean type represents truth values, either True or False.




# Q - 4 What is difference between mutable and immutable data types? How many data types are mutable or not ? please provide reason also with example ? 

In [14]:
Mutable Data Types:

Mutable data types are those whose values can be changed or modified after they are created.
When you modify a mutable object, you are working with the same object in memory.

Examples of mutable data types in Python include:

1.List:

Lists are ordered, mutable sequences.

2. Set:

Sets are unordered collections of unique elements.

3. Dictionary:

Dictionaries are collections of key-value pairs.

Immutable Data Types:

Immutable data types are those whose values cannot be changed after they are created.
When you "modify" an immutable object, you are actually creating a new object in memory.
Examples of immutable data types in Python include:
    
1. Integers:

Integer values cannot be changed once they are assigned.

2. Floats:

Floating-point numbers are immutable.

3. Tuples:

Tuples are ordered and immutable sequences.

4. Strings:

Strings are sequences of characters and are immutable.





SyntaxError: invalid decimal literal (2089062351.py, line 8)

In [12]:
# Example List
my_list = [1, 2, 3]
my_list[0] = 10
print(my_list)  # Output: [10, 2, 3]


[10, 2, 3]


In [15]:
# example Set

my_set = {1, 2, 3}
my_set.add(4)
print(my_set)  # Output: {1, 2, 3, 4}


{1, 2, 3, 4}


In [17]:
# example dict

my_dict = {'a': 1, 'b': 2}
my_dict['a'] = 10
print(my_dict)  # Output: {'a': 10, 'b': 2}


{'a': 10, 'b': 2}


# Q -5 Why we use loops ? Please provide 3 examples of for loop and 3 exaples of while loops? 

# Ans
Loops are used in programming to execute a set of statements or code repeatedly. They are essential for automating repetitive tasks and iterating over data structures. There are two main types of loops in Python: for loops and while loops.

Reasons for Using Loops:

Automation of Repetitive Tasks:

Loops allow you to execute a block of code repeatedly, reducing the need for redundant and repetitive coding.

Iteration Over Data Structures:

Loops provide an efficient way to iterate over elements in data structures such as lists, tuples, sets, and dictionaries.

Dynamic Control Flow:

Loops enable dynamic control flow based on conditions, allowing your program to adapt and respond to changing situations during execution.


In [23]:
exap

NameError: name 'exap' is not defined

In [25]:
# example for loop
numbers = [1, 2, 3, 4, 5]
for num in numbers:
    print(num)


1
2
3
4
5


In [27]:
# exapmle of while loop 
count = 5
while count > 0:
    print(count)
    count -= 1


5
4
3
2
1


# Q- 6 Why we use functions ? Difference between lambda , filter ,reduce , map function with example ?

# Ans - 

Functions allow you to break down your program into smaller, manageable pieces. 

Once a function is defined, it can be reused multiple times in different parts of your program. 

Functions can improve the readability of your code by giving meaningful names to different operations.

Difference Between lambda, filter, reduce, and map Functions:

1. lamda function
A lambda function is a small anonymous function.

A lambda function can take any number of arguments, but can only have one expression.

2. filter function
The filter function is used to filter elements of an iterable based on a function's condition.

3.reduce function
The reduce function is used to cumulatively apply a binary function to the items of an iterable, from left to right.
It is part of the functools module in Python 3.

4.map function
the map function applies a given function to all items in an iterable and returns an iterator of the results.

In summary, lambda is used for creating anonymous functions, filter is used for filtering elements, reduce is used for cumulative operations, and map is used for applying a function to all elements in an iterable. 


In [29]:
#examples of lamda function 

add = lambda x, y: x + y
print(add(2, 3))  


5


In [31]:
#examples of filter function
numbers = [1, 2, 3, 4, 5, 6]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)  


[2, 4, 6]


In [33]:
#example of reduce function
from functools import reduce
numbers = [1, 2, 3, 4, 5]        #(1*2=2, 2*3=6, 6*4=24, 24*5=120)
product = reduce(lambda x, y: x * y, numbers)
print(product)  


120


In [35]:
#example of map function
numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x: x**2, numbers))
print(squared_numbers)  

[1, 4, 9, 16, 25]


# Q- 7 Difference between list and tuple ? please provide index() , insert() , append() , reverse() examples in list ?

# Ans 

List vs. Tuple:
List:

Lists are mutable, meaning you can change their content (add, remove, or modify elements) after they are created.
Lists are defined using square brackets [].
Tuple:

Tuples are immutable, meaning their elements cannot be changed after the tuple is created.
Tuples are defined using parentheses ().

Examples of List Operations:
index():

The index() method returns the index of the first occurrence of a specified element in the list.

insert():

The insert() method inserts an element at a specified position in the list.

append():

The append() method adds an element to the end of the list.

reverse():

The reverse() method reverses the elements of the list in place.

in short
index(): Returns the index of the first occurrence of a specified element.
insert(): Inserts an element at a specified position.
append(): Adds an element to the end of the list.
reverse(): Reverses the order of elements in the list.

In [46]:
#example of index().

my_list = [10, 20, 30, 40, 30, 50]
index_40 = my_list.index(40)
print("Index of 40:", index_40)  # Output: Index of 40: 3


Index of 40: 3


In [40]:
#example of insert()

my_list = [1, 2, 3, 4, 5]
my_list.insert(2, 10)
print(my_list)  # Output: [1, 2, 10, 3, 4, 5]


[1, 2, 10, 3, 4, 5]


In [42]:
#example of append() 

my_list = [1, 2, 3]
my_list.append(4)
print(my_list)  # Output: [1, 2, 3, 4]


[1, 2, 3, 4]


In [44]:
#example of reverse()

my_list = [1, 2, 3, 4, 5]
my_list.reverse()
print(my_list)  # Output: [5, 4, 3, 2, 1]


[5, 4, 3, 2, 1]


# Q- 8 Difference between dictionary and set ? Please provide keys() , values() , items() example of dictionary and union() , intersection() in sets ? Is frozenset is mutable or not ? 

# Ans-

Dictionary vs. Set:

Dictionary:

A dictionary is an unordered collection of key-value pairs.
Each key in a dictionary must be unique.
Dictionaries are defined using curly braces {}.

Set:

A set is an unordered collection of unique elements.
Sets do not allow duplicate values.
Sets are defined using curly braces {} or the set() constructor

Dictionary Examples:
keys():

The keys() method returns a view of all the keys in the dictionary.

values():

The values() method returns a view of all the values in the dictionary.

items():

The items() method returns a view of all key-value pairs in the dictionary.


Set Examples:

union():

The union() method returns a new set containing all unique elements from both sets.

intersection():

The intersection() method returns a new set containing common elements from both sets.


A Frozen set

A frozenset is immutable, meaning you cannot add, remove, or modify elements after it is created.


In [48]:
#example of dictionary  
# 1 keys()

my_dict = {'a': 1, 'b': 2, 'c': 3}
key_view = my_dict.keys()
print(key_view)  # Output: dict_keys(['a', 'b', 'c'])


dict_keys(['a', 'b', 'c'])


In [49]:
#example of dictionary  
# 2 values()

my_dict = {'a': 1, 'b': 2, 'c': 3}
value_view = my_dict.values()
print(value_view)  # Output: dict_values([1, 2, 3])


dict_values([1, 2, 3])


In [51]:
#example of dictionary  
# 3 items()

my_dict = {'a': 1, 'b': 2, 'c': 3}
items_view = my_dict.items()
print(items_view)  # Output: dict_items([('a', 1), ('b', 2), ('c', 3)])


dict_items([('a', 1), ('b', 2), ('c', 3)])


In [52]:
#examples of set
# 1 union()

set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1.union(set2)
print(union_set)  # Output: {1, 2, 3, 4, 5}


{1, 2, 3, 4, 5}


In [53]:
#examples of set
# 2  intersection()

set1 = {1, 2, 3}
set2 = {3, 4, 5}
intersection_set = set1.intersection(set2)
print(intersection_set)  # Output: {3}


{3}


In [54]:
# example of sets 

# Frozen set

frozen_set = frozenset([1, 2, 3])
print(frozen_set)  # Output: frozenset({1, 2, 3})


frozenset({1, 2, 3})


# Q- 9 What are decorators ? Please provide examples ?

# Ans- 

In Python, a decorator is a special type of function that can be used to modify the behavior of another function. Decorators are often used to extend or enhance the functionality of functions without modifying their actual code. They provide a way to wrap a function with additional logic or functionality.

The syntax for using decorators involves placing the decorator symbol @ above the function definition. Here's a simple example of a decorator:


# Q- 10 What are list comprehension ? Please provide examples ?

# Ans-

List comprehensions are a concise and expressive way to create lists in Python. They provide a more readable and compact syntax for generating lists by applying an expression to each item in an iterable (e.g., a list, tuple, or string). List comprehensions consist of an expression followed by at least one for clause and zero or more if clauses.



In [56]:
#Example 1: Basic List Comprehension

# Creating a list of squares for numbers from 0 to 9
squares = [x**2 for x in range(10)]
print(squares)
# Output: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [57]:
#Example 2: List Comprehension with Condition

# Creating a list of even numbers from 0 to 9

even_numbers = [x for x in range(10) if x % 2 == 0]
print(even_numbers)  # Output: [0, 2, 4, 6, 8]



[0, 2, 4, 6, 8]


In [58]:
#Example 3: Nested List Comprehension

# Creating a list of tuples representing Cartesian coordinates

cartesian_coordinates = [(x, y) for x in range(2) for y in range(2)]
print(cartesian_coordinates)      # Output: [(0, 0), (0, 1), (1, 0), (1, 1)]



[(0, 0), (0, 1), (1, 0), (1, 1)]


In [59]:
#Example 4: List Comprehension with Condition and Expression

# Creating a list of squares for even numbers from 0 to 9

squares_of_evens = [x**2 for x in range(10) if x % 2 == 0]
print(squares_of_evens)                  # Output: [0, 4, 16, 36, 64]



[0, 4, 16, 36, 64]


In [60]:
#Example 5: List Comprehension with a Function

# Creating a list of lengths of words in a sentence
sentence = "List comprehensions are powerful"
word_lengths = [len(word) for word in sentence.split()]
print(word_lengths)
# Output: [4, 14, 3, 8]


[4, 14, 3, 8]


# Q- 11 How do you create an array from a user defined list ?

# Ans- 

In Python, you can create an array from a user-defined list using the array module, which provides an array type that is similar to a list but with some differences, such as being more memory-efficient for certain types of operations.




In [61]:
from array import array

# User-defined list
user_list = [1, 2, 3, 4, 5]

# Creating an array from the list (assuming integer values)
user_array = array('i', user_list)

# Displaying the array
print(user_array)


array('i', [1, 2, 3, 4, 5])


# Q- 12 Difference between hstack() and vstack()  with example?

# Ans -
In NumPy, hstack() and vstack() are functions used to concatenate arrays horizontally and vertically, respectively.

numpy.hstack()

The hstack() function is used to stack arrays in sequence horizontally (column-wise). It takes a tuple or a list of arrays as an argument and returns a single array.


numpy.vstack()

The vstack() function is used to stack arrays in sequence vertically (row-wise). Like hstack(), it takes a tuple or a list of arrays as an argument and returns a single array.



In [62]:

#Example hstack()

import numpy as np

# Creating two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Horizontally stacking the arrays
result = np.hstack((arr1, arr2))

print(result)
# Output: [1 2 3 4 5 6]


#In this example, arr1 and arr2 are horizontally stacked to create a new array result with elements [1, 2, 3, 4, 5, 6].

[1 2 3 4 5 6]


In [63]:
#Example vstack()

import numpy as np

# Creating two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertically stacking the arrays
result = np.vstack((arr1, arr2))

print(result)
# Output:
# [[1 2 3]
#  [4 5 6]]


#In this example, arr1 and arr2 are vertically stacked to create a new 2D array result with rows 
[[1, 2, 3], 
 [4, 5, 6]].

[[1 2 3]
 [4 5 6]]


# Q-13 What is zeros() , ones() , eye() , diag() , randint() , rand() , seed() , linspace() , unique() in NumPy ? Please provide 1-1 examples of these functions ? 

In [65]:
#numpy.zeros()

#The zeros() function creates an array filled with zeros.

import numpy as np

# Create a 1D array of zeros
zeros_array = np.zeros(5)
print(zeros_array)
# Output: [0. 0. 0. 0. 0.]


[0. 0. 0. 0. 0.]


In [66]:
#numpy.ones()
#The ones() function creates an array filled with ones.

import numpy as np

# Create a 2D array of ones
ones_array = np.ones((2, 3))
print(ones_array)
# Output:
# [[1. 1. 1.]
#  [1. 1. 1.]]


[[1. 1. 1.]
 [1. 1. 1.]]


In [67]:
#numpy.eye()

#The eye() function creates an identity matrix (a square matrix with ones on the main diagonal and zeros elsewhere).

import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
#numpy.diag()

#The diag() function extracts the diagonal or constructs a diagonal array.

import numpy as np

# Create a 3x3 array and extract its diagonal
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal_elements = np.diag(matrix)
print(diagonal_elements)
# Output: [1 5 9]


[1 5 9]


In [70]:
#numpy.randint()

#The randint() function generates random integers from a specified low (inclusive) to a specified high (exclusive).

import numpy as np

# Generate a random integer between 1 (inclusive) and 10 (exclusive)
random_integer = np.random.randint(1, 10)
print(random_integer)
# Output: a random integer between 1 and 9


3


In [73]:
#numpy.rand()

#The rand() function generates random numbers from a uniform distribution over [0, 1).

import numpy as np

# Generate a random number between 0 and 1
random_number = np.random.rand()
print(random_number)
# Output: a random float between 0 and 1


0.45165457327655645


In [76]:
#numpy.seed()

#The seed() function sets the seed for NumPy's pseudo-random number generator. This is useful for reproducibility.

import numpy as np

# Set the seed for reproducibility
np.random.seed(42)

# Generate two random numbers
random1 = np.random.rand()
random2 = np.random.rand()

print(random1, random2)
# Output: two reproducible random numbers


0.3745401188473625 0.9507143064099162


In [77]:
#numpy.linspace()

#The linspace() function creates an array of evenly spaced values over a specified range.

import numpy as np

# Create an array of 5 values evenly spaced between 0 and 1
evenly_spaced_values = np.linspace(0, 1, 5)
print(evenly_spaced_values)
# Output: [0.   0.25 0.5  0.75 1.  ]


[0.   0.25 0.5  0.75 1.  ]


In [78]:
#numpy.unique()

#The unique() function returns the unique elements of an array.

import numpy as np

# Create an array with repeated elements
arr = np.array([1, 2, 2, 3, 4, 4, 5])

# Get the unique elements
unique_elements = np.unique(arr)
print(unique_elements)
# Output: [1 2 3 4 5]



[1 2 3 4 5]


# Q- 14 How can you reshape your array in numpy ? Please provide example also ?

# Ans-
In NumPy, the reshape() function is used to change the shape of an array. It returns a new array with the same data but a different shape. The reshape() function takes the desired shape as its argument.

In [80]:
import numpy as np

# Create a 1D array with 12 elements
original_array = np.arange(12)
print("Original 1D array:")
print(original_array)

# Reshape the array to a 3x4 matrix
reshaped_array = original_array.reshape(3, 4)
print("\nReshaped 2D array:")
print(reshaped_array)


Original 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Q- 15 what is argmin() and argmax() in numpy ? please exaplain using an example ?

# Ans-
In NumPy, argmin() and argmax() are functions that return the indices of the minimum and maximum values, respectively, along a specified axis. These functions are useful for finding the position (index) of the minimum and maximum elements in an array.

In [81]:
#Example using argmin():

import numpy as np

# Create a 1D array
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# Find the index of the minimum element
min_index = np.argmin(arr)
print("Index of minimum element:", min_index)


Index of minimum element: 1


In [82]:
#Example using argmax():

import numpy as np

# Create a 1D array
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# Find the index of the maximum element
max_index = np.argmax(arr)
print("Index of maximum element:", max_index)


Index of maximum element: 5
